public class demoWhileDoWhile {
    


    //okadym


    public void demoWhile(){
        Integer count = 1;
        
        while(count<11){
            system.debug('Count: ' + count);
            count ++;
        }
    }
    
    public void demoDoWhile(){
        Integer count = 1;
        
        do{
            system.debug('value: ' + count);
            count++;
        }while(count < 11);
    }
    

}